<?php

return [
    [
        'name' => 'Milo',
        'surname' => 'Marziali',
        'address' => 'Via Pompeo, 7',
        'photo' => 'https://picsum.photos/200/300',
        'curriculum_vitae' => 'curriculum',
        'cell_number' => '3202486129',
        'services' => "Scienze dell'Alimentazione, Medicina estetica, Terapia del dolore",
    ],
    [
        'name' => 'Cristian',
        'surname' => 'Pellegrini',
        'address' => 'Via Lodovico, 15',
        'photo' => 'https://picsum.photos/200/300',
        'curriculum_vitae' => 'curriculum',
        'cell_number' => '3985421605',
        'services' => 'Ecocolordoppler dei vasi periferici, Ecocolordoppler dei tronchi sovra aortici, Elettrocardiogramma holter',
    ],
    [
        'name' => 'Marco',
        'surname' => 'Zampieri',
        'address' => 'Via degli Oleandri, 11',
        'photo' => 'https://picsum.photos/200/300',
        'curriculum_vitae' => 'curriculum',
        'cell_number' => '3201542097',
        'services' => 'Coronarografia, Cataratta, Visita oculistica',
    ],
    [
        'name' => 'Vilma Maria',
        'surname' => 'Crivellaro',
        'address' => 'Via Baggio, 20',
        'photo' => 'https://picsum.photos/200/300',
        'curriculum_vitae' => 'curriculum',
        'cell_number' => '3501248961',
        'services' => 'Radiografia ossea e delle articolazioni, Radiografia completa del tubo digerente, Radiografia completa del tubo digerente',
    ],
    [
        'name' => 'Giorgio',
        'surname' => 'Francuzzi',
        'address' => 'Via Mar Nero, 30',
        'photo' => 'https://picsum.photos/200/300',
        'curriculum_vitae' => 'curriculum',
        'cell_number' => '3340245986',
        'services' => 'Riabilitazione motoria, Riabilitazione respiratoria, Logopedia',
    ],
    [
        'name' => 'Martina',
        'surname' => 'Seravelli',
        'address' => 'Viale Nazario Sauro, 5',
        'photo' => 'https://picsum.photos/200/300',
        'curriculum_vitae' => 'curriculum',
        'cell_number' => '33012547842',
        'services' => 'Visita neurologica, EEG, EMG, Potenziali Evocati',
    ],
    [
        'name' => 'Mariarosa',
        'surname' => 'Romeo',
        'address' => 'Via Ugo Bassi, 22',
        'photo' => 'https://picsum.photos/200/300',
        'curriculum_vitae' => 'curriculum',
        'cell_number' => '3334869977',
        'services' => 'Visita dermatologica, Test allergologici',
    ],
    [
        'name' => 'Sergio',
        'surname' => 'Piombino',
        'address' => 'Via Giulio Cesare Procaccini, 4',
        'photo' => 'https://picsum.photos/200/300',
        'curriculum_vitae' => 'curriculum',
        'cell_number' => '3398456211',
        'services' => 'Impedenzometria, Potenziali evocati, Test vestibolare',
    ],
    [
        'name' => 'Carla',
        'surname' => 'Rando',
        'address' => 'Via Monte Amiata, 9',
        'photo' => 'https://picsum.photos/200/300',
        'curriculum_vitae' => 'curriculum',
        'cell_number' => '3154206974',
        'services' => 'Colloquio psichiatrico, Elettroencefalogramma, Visita neurologica',
    ],
    [
        'name' => 'Chiara',
        'surname' => 'Pirozzi',
        'address' => 'Via Alfonso Lamarmora, 8',
        'photo' => 'https://picsum.photos/200/300',
        'curriculum_vitae' => 'curriculum',
        'cell_number' => '3342018799',
        'services' => "Visita ginecologica, Test HPV, Ecografia, Possibilità di praticare l'aborto",
    ],
]

?>