<?php

return [
    [
        'email'=>'milomarziali@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'MiloMarziali',
        'user_id' => '1',
        'name' => 'Milo',
        'surname' => 'Marziali',
        'address' => 'Via Pompeo, 7',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3202486129',
        'services' => "Scienze dell'Alimentazione, Medicina estetica, Terapia del dolore",
    ],
    [
        'email'=>'cristianpellegrini@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'CristianPellegrini',
        'user_id' => '2',
        'name' => 'Cristian',
        'surname' => 'Pellegrini',
        'address' => 'Via Lodovico, 15',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3985421605',
        'services' => 'Ecocolordoppler dei vasi periferici, Ecocolordoppler dei tronchi sovra aortici, Elettrocardiogramma holter',
    ],
    [
        'email'=>'marcozampieri@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'MarcoZampieri',
        'user_id' => '3',
        'name' => 'Marco',
        'surname' => 'Zampieri',
        'address' => 'Via degli Oleandri, 11',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3201542097',
        'services' => 'Coronarografia, Trattamento cataratta, Visita oculistica',
    ],
    [
        'email'=>'vilmamaria@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'VilmaMaria',
        'user_id' => '4',
        'name' => 'Vilma Maria',
        'surname' => 'Crivellaro',
        'address' => 'Via Baggio, 20',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3501248961',
        'services' => 'Radiografia ossea e delle articolazioni, Radiografia completa del tubo digerente, Radiografia completa del tubo digerente',
    ],
    [
        'email'=>'giorgiofrancuzzi@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'GiorgioFrancuzzi',
        'user_id' => '5',
        'name' => 'Giorgio',
        'surname' => 'Francuzzi',
        'address' => 'Via Mar Nero, 30',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3340245986',
        'services' => 'Riabilitazione motoria, Riabilitazione respiratoria, Logopedia',
    ],
    [
        'email'=>'martinaseravelli@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'MartinaSeravelli',
        'user_id' => '6',
        'name' => 'Martina',
        'surname' => 'Seravelli',
        'address' => 'Viale Nazario Sauro, 5',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '33012547842',
        'services' => 'Visita neurologica, EEG, EMG, Potenziali Evocati',
    ],
    [
        'email'=>'mariarosaromeo@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'MartinaRomeo',
        'user_id' => '7',
        'name' => 'Mariarosa',
        'surname' => 'Romeo',
        'address' => 'Via Ugo Bassi, 22',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3334869977',
        'services' => 'Visita dermatologica, Test allergologici',
    ],
    [
        'email'=>'sergiopiombino@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'SergioPiombino',
        'user_id' => '8',
        'name' => 'Sergio',
        'surname' => 'Piombino',
        'address' => 'Via Giulio Cesare Procaccini, 4',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3398456211',
        'services' => 'Impedenzometria, Potenziali evocati, Test vestibolare',
    ],
    [
        'email'=>'carlarando@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'CarlaRando',
        'user_id' => '9',
        'name' => 'Carla',
        'surname' => 'Rando',
        'address' => 'Via Monte Amiata, 9',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3154206974',
        'services' => 'Colloquio psichiatrico, Elettroencefalogramma, Visita neurologica',
    ],
    [
        'email'=>'chiarapirozzi@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'ChiaraPirozzi',
        'user_id' => '10',
        'name' => 'Chiara',
        'surname' => 'Pirozzi',
        'address' => 'Via Alfonso Lamarmora, 8',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3342018799',
        'services' => "Visita ginecologica, Test HPV, Ecografia, Possibilità di praticare l'aborto",
    ],
    [
        'email'=>'giorgiamarconi@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'GiorgiaMarconi',
        'user_id' => '11',
        'name' => 'Giorgia',
        'surname' => 'Marconi',
        'address' => 'Via Fata Morgana, 22',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3351278496',
        'services' => "Ecografia toracica, ecografia capo e collo",
    ],
    [
        'email'=>'simonerossi@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'SimoneRossi',
        'user_id' => '12',
        'name' => 'Simone',
        'surname' => 'Rossi',
        'address' => 'Via Napoleone, 17',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3334587799',
        'services' => "Analisi campo visivo, Fluorangiografia",
    ],
    [
        'email'=>'giorgiograsso@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'GiorgioGrasso',
        'user_id' => '13',
        'name' => 'Giorgio',
        'surname' => 'Grasso',
        'address' => 'Via dei Mille, 44',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3698541267',
        'services' => "Impedenzometria, Potenziali evocati acustici, Test vestibolare",
    ],
    [
        'email'=>'sarapanebianco@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'SaraPanebianco',
        'user_id' => '14',
        'name' => 'Sara',
        'surname' => 'Panebianco',
        'address' => 'Viale della Libertà, 18',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3312444569',
        'services' => "Logopedia",
    ],
    [
        'email'=>'giorgiovalli@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'GiorgioValli',
        'user_id' => '15',
        'name' => 'Giorgio',
        'surname' => 'Valli',
        'address' => 'Via Risorgimento, 1',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3342115587',
        'services' => "Elettroencefalogramma, Elettromiografia, Visita Neurologica",
    ],
    [
        'email'=>'marcolori@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'MarcoLori',
        'user_id' => '16',
        'name' => 'Marco',
        'surname' => 'Lori',
        'address' => 'Via Melchiorre, 22',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3314587722',
        'services' => "Test allergologici",
    ],
    [
        'email'=>'mariacarlaserafini@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'MariacarlaSerafini',
        'user_id' => '17',
        'name' => 'Mariacarla',
        'surname' => 'Serafini',
        'address' => 'Via Marco Polo, 15',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3325584624',
        'services' => "TC Collo, TC Rene, TC Massiccio Facciale",
    ],
    [
        'email'=>'francoscoglio@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'FrancoScoglio',
        'user_id' => '18',
        'name' => 'Franco',
        'surname' => 'Scoglio',
        'address' => 'Viale della Panoramica, 11',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '332669485',
        'services' => "Urografia endovenosa, Radiografia ossea e delle articolazioni",
    ],
    [
        'email'=>'giuseppecalogero@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'GiuseppeCalogero',
        'user_id' => '19',
        'name' => 'Giuseppe',
        'surname' => 'Calogero',
        'address' => 'Via Noviziato, 2',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3369995482',
        'services' => "RM Torace e miocardio, RM Muscoloscheletrica",
    ],
    [
        'email'=>'antoniomirulla@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'AntonioMirulla',
        'user_id' => '20',
        'name' => 'Antonio',
        'surname' => 'Mirulla',
        'address' => 'Via delle Lucciole, 11',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '332745698',
        'services' => "Colloquio psichiatrico, Elettroencefalogramma, Visita neurologica",
    ],
    [
        'email'=>'orianafranchi@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'OrianaFranchi',
        'user_id' => '21',
        'name' => 'Oriana',
        'surname' => 'Franchi',
        'address' => 'Viale Gazzi, 5',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3312599864',
        'services' => "Impedenzometria, Potenziali evocati acustici, Test vestibolare",
    ],
    [
        'email'=>'alessandrogiorgi@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'AlessandroGiorgi',
        'user_id' => '22',
        'name' => 'Alessandro',
        'surname' => 'Giorgi',
        'address' => 'Via del Fante, 8',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3312254896',
        'services' => "Coronarografia, Trattamento cataratta, Visita oculistica",
    ],
    [
        'email'=>'elenadenici@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'ElenaDenici',
        'user_id' => '23',
        'name' => 'Elena',
        'surname' => 'Denici',
        'address' => 'Via Alfonso Lamarmora, 8',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3324415578',
        'services' => "Analisi campo visivo, Fluorangiografia",
    ],
    [
        'email'=>'rossanasaruzzi@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'RossanaSaruzzi',
        'user_id' => '24',
        'name' => 'Rossana',
        'surname' => 'Saruzzi',
        'address' => 'Via delle vespe, 12',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3387456695',
        'services' => "Ecocolordoppler dei vasi periferici, Ecocolordoppler dei tronchi sovra aortici, Elettrocardiogramma holter",
    ],
    [
        'email'=>'marcopalmara@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'MarcoPalmara',
        'user_id' => '25',
        'name' => 'Marco',
        'surname' => 'Palmara',
        'address' => 'Contrada Cicerina, 6',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3345988766',
        'services' => "Visita ginecologica, Test HPV, Ecografia, Possibilità di praticare l'aborto",
    ],
    [
        'email'=>'carlottamarmora@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'CarlottaMarmora',
        'user_id' => '26',
        'name' => 'Carlotta',
        'surname' => 'Marmora',
        'address' => 'Via Colli S. Rizzo, 7',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3342018799',
        'services' => "Visita dermatologica, Test allergologici",
    ],
    [
        'email'=>'biagioleori@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'BiagioLeori',
        'user_id' => '27',
        'name' => 'Biagio',
        'surname' => 'Leori',
        'address' => 'Viale S. Martino, 19',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3339985472',
        'services' => "Riabilitazione motoria, Riabilitazione respiratoria, Logopedia",
    ],
    [
        'email'=>'paolomeneguzzi@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'PaoloMeneguzzi',
        'user_id' => '28',
        'name' => 'Paolo',
        'surname' => 'Mneguzzi',
        'address' => 'Via Ugo Bassi, 33',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3226599861',
        'services' => "Ecocolordoppler dei vasi periferici, Ecocolordoppler dei tronchi sovra aortici, Elettrocardiogramma holter",
    ],
    [
        'email'=>'francescabartolini@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'FrancescaBartolini',
        'user_id' => '29',
        'name' => 'Francesca',
        'surname' => 'Bartolini',
        'address' => 'Via Boner, 11',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3336985584',
        'services' => "RM Torace e miocardio, RM Muscoloscheletrica, RM colonna vertebrale",
    ],
    [
        'email'=>'giuliarovere@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'GiuliaRovere',
        'user_id' => '30',
        'name' => 'Giulia',
        'surname' => 'Rovere',
        'address' => 'Via Tommaso Cannizzaro, 6',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3696551240',
        'services' => "Colloquio psichiatrico, Elettroencefalogramma, Visita neurologica",
    ],
    [
        'email'=>'bernardodalia@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'BernardoDalia',
        'user_id' => '31',
        'name' => 'Bernardo',
        'surname' => 'Dalia',
        'address' => 'Via Missori, 8',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3669854110',
        'services' => "Radiografia ossea e delle articolazioni, Radiografia completa del tubo digerente, Radiografia completa del tubo digerente",
    ],
    [
        'email'=>'emanueleallegra@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'EmanueleAllegra',
        'user_id' => '32',
        'name' => 'Emanuele',
        'surname' => 'Allegra',
        'address' => 'Viale delle donnole, 11',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3021220445',
        'services' => "TC Collo, TC Rene, TC Massiccio Facciale",
    ],
    [
        'email'=>'simonademeo@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'SimonaDemeo',
        'user_id' => '33',
        'name' => 'Simona',
        'surname' => 'De Meo',
        'address' => 'Via Minici, 15',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '33100526999',
        'services' => "Visita ginecologica, Test HPV, Ecografia, Possibilità di praticare l'aborto",
    ],
    [
        'email'=>'carlaminici@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'CarlaMinici',
        'user_id' => '34',
        'name' => 'Carla',
        'surname' => 'Minici',
        'address' => 'Via dei Portici, 22',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3330015774',
        'services' => "Scienze dell'Alimentazione, Medicina estetica, Terapia del dolore",
    ],
    [
        'email'=>'alessandradantoni@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'AlessandraDantoni',
        'user_id' => '35',
        'name' => 'Alessandra',
        'surname' => 'Dantoni',
        'address' => 'Via Merrini, 1',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3306958842',
        'services' => "Riabilitazione motoria, Riabilitazione respiratoria, Logopedia",
    ],
    [
        'email'=>'silviaformini@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'SilviaFormini',
        'user_id' => '36',
        'name' => 'Silvia',
        'surname' => 'Formini',
        'address' => 'Piazza del Popolo, 7',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3339953012',
        'services' => "Radiografia ossea e delle articolazioni, Radiografia completa del tubo digerente, Radiografia completa del tubo digerente",
    ],
    [
        'email'=>'francescobottari@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'FrancescoBottari',
        'user_id' => '37',
        'name' => 'Francesco',
        'surname' => 'Bottari',
        'address' => 'Via Santa Marta, 44',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3669980120',
        'services' => "Visita neurologica, EEG, EMG, Potenziali Evocati",
    ],
    [
        'email'=>'marcovieri@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'MarcoVieri',
        'user_id' => '38',
        'name' => 'Marco',
        'surname' => 'Vieri',
        'address' => 'Piazza Plebiscito, 4',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3310024789',
        'services' => "Visita ginecologica, Test HPV, Ecografia, Possibilità di praticare l'aborto",
    ],
    [
        'email'=>'emilynovik@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'EmilyNovik',
        'user_id' => '39',
        'name' => 'Emily',
        'surname' => 'Novik',
        'address' => 'Via Marconi, 15',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3338756921',
        'services' => "Scienze dell'Alimentazione, Medicina estetica, Terapia del dolore",
    ],
    [
        'email'=>'oraziosordi@dottori.com',
        'password'=>'doctors59',
        'user_name' => 'OrazioSordi',
        'user_id' => '40',
        'name' => 'Orazio',
        'surname' => 'Sordi',
        'address' => 'Via Melchiorre, 9',
        'photo' => '',
        'curriculum_vitae' => '',
        'cell_number' => '3312006745',
        'services' => "Coronarografia, Trattamento cataratta, Visita oculistica",
    ],
]

?>